import numpy as np
from abc import ABC, abstractmethod
from typing import Any, Dict, Iterator, List, Optional, Union
from sciql.core.data import Frame
from sciql.core.data import Sampler

class Agent(ABC):

    """
    Absract class to define an agent.
    """
    
    def reset(self, seed: Optional[int] = None, **kwargs) -> "Agent":
        """
        Resets the interface and the policy with a new seed and any additional arguments.

        Args:
            seed (Optional[int]): New seed for random number generators. Defaults to None.

        Returns:
            (Agent): The instance of this agent after reset.
        """
        raise NotImplementedError
    
    @abstractmethod
    def act(self, frame: Union[Dict[str, np.ndarray],Frame], **kwargs) -> Frame:
        """
        Generates an action based on the input frame.

        Args:
            frame (Frame): The input frame for generating an action.

        Returns:
            (Frame): The output frame containing the action generated by the policy.
        """
        raise NotImplementedError
    
    def update(self, sampler: Sampler, **kwargs) -> Dict:
        """
        Performs a policy update based on the input batch (one gradient step).

        Args:
            sampler: The sampler from which to get the batch.

        Returns:
            (Dict): The computed loss(es) for the policy.
        """
        raise NotImplementedError
    
    def to(self, device) -> "Agent":
        """
        Moves the policy to a specified device (CPU or GPU).

        Args:
            device: The target device.

        Returns:
            (Agent): The agent with its policy moved to the specified device.
        """
        raise NotImplementedError
    
    def set_train_mode(self, **kwargs) -> "Agent":
        """
        Sets the policy to training mode.

        Returns:
            (Agent): The agent with its policy set to training mode.
        """
        raise NotImplementedError

    def set_eval_mode(self, **kwargs) -> "Agent":
        """
        Sets the policy to evaluation mode.

        Returns:
            (Agent): The agent with its policy set to evaluation mode.
        """
        raise NotImplementedError
    
    def parameters(self) -> Iterator:
        """
        Returns an iterator over the policy's parameters.

        Returns:
            (Iterator): An iterator over the policy's parameters.
        """
        raise NotImplementedError
    
    def inference_parameters(self) -> Iterator:
        """
        Returns an iterator over model parameters used for inference.

        Returns:
            (Iterator[nn.Parameter]): An iterator over the model parameters used for inference.
        """
        raise NotImplementedError
    
    def buffers(self) -> Iterator:
        """
        Returns an iterator over all model buffers.

        Returns:
            (Iterator): An iterator over the model buffers.
        """
        raise NotImplementedError

    def inference_buffers(self) -> Iterator:
        """
        Returns an iterator over model buffers used for inference.

        Returns:
            (Iterator): An iterator over the model buffers used for inference.
        """
        raise NotImplementedError

    def size(self) -> float:
        """
        Calculates the total size of the policy's parameters and buffers in megabytes (MB).

        Returns:
            (float): The total size of the policy in MB.
        """
        raise NotImplementedError
    
    def inference_size(self) -> float:
        """
        Calculates the size of the policy's parameters and buffers used for inference in MB.

        Returns:
            (float): The size of the policy for inference in MB.
        """
        raise NotImplementedError

    def __getstate__(self) -> Dict[str, Any]:
        """
        Gets the state of the agent.

        Returns:
            (Dict[str, Any]): The state of the agent.
        """
        raise NotImplementedError

    def __setstate__(self, state: Dict[str, Any]) -> None:
        """
        Sets the state of the agent.

        Args:
            state (Dict[str, Any]): The state of the agent.
        """
        raise NotImplementedError


class AgentsDB(ABC):

    """
    Abstract base class for a database of agents.
    """

    @abstractmethod
    def __init__(self) -> None:
        raise NotImplementedError

    @abstractmethod
    def __contains__(self, agent_id: str) -> bool:
        """
        Check if an agent is in the database.

        Args:
            agent_id (str): The ID of the agent.

        Returns:
            (bool): True if the agent is in the database, False otherwise.
        """
        raise NotImplementedError

    @abstractmethod
    def __repr__(self) -> str:
        """
        Get a string representation of the database.

        Returns:
            (str): A string representation of the database.
        """
        raise NotImplementedError

    @abstractmethod
    def add_agent(self, agent: Agent, agent_id: str, agent_stage: int) -> None:
        """
        Add an agent to the database with a given ID and stage.

        Args:
            agent (Agent): The agent to add.
            agent_id (str): The ID of the agent.
            agent_stage (int): The stage of the agent.
        """
        raise NotImplementedError

    @abstractmethod
    def delete_agent(self, agent_id: str, agent_stage: int = None) -> None:
        """
        Delete an agent from the database (all stages if None is provided).

        Args:
            agent_id (str): The ID of the agent.
            agent_stage (int): The stage of the agent (if None, delete all stages). Default to None.

        Returns:
            (None): Nothing.
        """
        raise NotImplementedError

    @abstractmethod
    def get_ids(self) -> List[str]:
        """
        Get the IDs of the agents in the database.

        Returns:
            (List[str]): The IDs of the agents in the database.
        """
        raise NotImplementedError

    @abstractmethod
    def get(self, agent_id: str, agent_stage: int) -> Agent:
        """
        Get an agent by ID and stage.

        Args:
            agent_id (str): The ID of the agent.
            agent_stage (int): The stage of the agent.

        Returns:
            (Agent): The agent with the given ID and stage.
        """
        raise NotImplementedError

    @abstractmethod
    def get_first_stage(self, agent_id: str) -> "Agent":
        """
        Get the first stage of an agent with a given ID.

        Args:
            agent_id (str): The ID of the agent.

        Returns:
            (Agent): The first agent with the given ID.
        """
        raise NotImplementedError

    @abstractmethod
    def get_last_stage(self, agent_id: str) -> "Agent":
        """
        Get the last stage of an agent with a given ID.

        Args:
            agent_id (str): The ID of the agent.

        Returns:
            (Agent): The last agent with the given ID.
        """
        raise NotImplementedError
    
    @abstractmethod
    def stages(self, agent_id: str) -> List[int]:
        """
        Returns the stages of the specified agent.

        Args:
            agent_id (str): The agent ID.

        Returns:
            (List[int]): The stages of the specified agent
        """
        raise NotImplementedError
    



